language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
    - "pip install -U pip setuptools"
    - "pip install -r requirements.txt"
    - "pip install ."
# command to run tests
script: py.test
