---
- name: create database
  command: "mysql -uroot -p{{ percona_root_password }} -e 'CREATE DATABASE IF NOT EXISTS {{ fosstp_db_name }} CHARSET utf8mb4'"
- name: create database account
  command: "mysql -uroot -p{{ percona_root_password }} -e 'GRANT ALL ON {{ fosstp_db_name }}.* TO {{ fosstp_db_user }}@localhost IDENTIFIED BY \"{{ fosstp_db_pass }}\"'"
- name: unarchive mysql-connector-python package
  unarchive:
    src: "https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.3.tar.gz"
    dest: "/tmp"
    copy: no
- name: install mysql-connector-python manually
  command: "{{ wsgiapp_basedir }}/venv/bin/python /tmp/mysql-connector-python-2.1.3/setup.py install"
  args:
    chdir: "/tmp/mysql-connector-python-2.1.3"
- name: generate random string
  shell: "date +%s | sha256sum | base64 | head -c 32 ; echo"
  register: random_string    
- name: setup ini config
  template:
    src: "production.ini.j2"
    dest: "{{ wsgiapp_basedir }}/production.ini"
    owner: "www-data"
    group: "www-data"
    mode: "0600"
