"""init

Revision ID: 257b87870423
Revises: 
Create Date: 2016-11-23 01:41:06.716843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257b87870423'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    op.bulk_insert(users_table,
        [
            {'id': 1, 'name': 'admin',
                      'password': '$2b$12$OUCC1PDBsg305zzY5KaR5uR14./Ohsopd1K2usCb05iewLtY1Bb6S',
                      'group': 'admin', 'email': 'fosstp@gmail.com'},
        ]
    )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop')
    op.drop_table('users')
    ### end Alembic commands ###
