"""add planet content model

Revision ID: 451b15ef88af
Revises: 2719d9778a6d
Create Date: 2016-11-25 06:13:58.520006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451b15ef88af'
down_revision = '2719d9778a6d'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet_contents')
    ### end Alembic commands ###
