"""add datetime to forum models

Revision ID: f3927c7ad77e
Revises: e32bf2e2b443
Create Date: 2016-11-24 01:44:05.894107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3927c7ad77e'
down_revision = 'e32bf2e2b443'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_replies', sa.Column('create_datetime', sa.DateTime()))
    op.add_column('forum_topics', sa.Column('create_datetime', sa.DateTime()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_topics', 'create_datetime')
    op.drop_column('forum_replies', 'create_datetime')
    ### end Alembic commands ###
